/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:cd6e9b46-bf57-4555-8f17-1a2c0aec8525",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_tLV3eNDUY",
    "aws_user_pools_web_client_id": "2mrvo6bh92ov311dod4mdilg0a",
    "oauth": {}
};


export default awsmobile;
